version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:${PORT}
    volumes:
      - .:/usr/src/app/
    ports:
      - ${PORT}:${PORT}
    env_file:
      - docker.env
      - .env
    environment:
      - DJANGOPROJECT_DATA_DIR=./data
      # - DJANGO_SETTINGS_MODULE=djangoproject.settings.docker
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_HOST=${SQL_HOST:-db}
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${SQL_DATABASE}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
