"""empty message

Revision ID: 04c671946978
Revises: cb11801285ea
Create Date: 2020-10-31 16:37:51.751693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c671946978'
down_revision = 'cb11801285ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_competences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competences_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competences_id'], ['competences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('competences', sa.Column('turns', sa.Integer(), nullable=True))
    op.drop_column('competences', 'amount_turned')
    op.drop_column('competences', 'classification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competences', sa.Column('classification', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('competences', sa.Column('amount_turned', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('competences', 'turns')
    op.drop_table('user_competences')
    # ### end Alembic commands ###
