"""empty message

Revision ID: 0e9e7452d913
Revises: ea2b942347df
Create Date: 2021-05-02 14:05:29.770210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9e7452d913'
down_revision = 'ea2b942347df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'duration')
    # ### end Alembic commands ###
