"""empty message

Revision ID: 0faa44d99b07
Revises: 3e8d09a7738b
Create Date: 2020-11-04 11:13:38.121048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0faa44d99b07'
down_revision = '3e8d09a7738b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competences', sa.Column('name_competence', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competences', 'name_competence')
    # ### end Alembic commands ###
