"""empty message

Revision ID: 254dc00e3835
Revises: 5175ef5f5d3c
Create Date: 2021-03-23 20:04:23.327126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254dc00e3835'
down_revision = '5175ef5f5d3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dateBirth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dateBirth')
    # ### end Alembic commands ###
