"""empty message

Revision ID: 3e8d09a7738b
Revises: 942b3518a849
Create Date: 2020-10-31 18:08:43.258389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8d09a7738b'
down_revision = '942b3518a849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('competences_user_id_fkey', 'competences', type_='foreignkey')
    op.drop_column('competences', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competences', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('competences_user_id_fkey', 'competences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
