"""empty message

Revision ID: 942b3518a849
Revises: 04c671946978
Create Date: 2020-10-31 16:49:01.025461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942b3518a849'
down_revision = '04c671946978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competences', 'duration_minutes')
    op.drop_column('competences', 'turns')
    op.add_column('user_competences', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('user_competences', sa.Column('turns', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_competences', 'turns')
    op.drop_column('user_competences', 'duration')
    op.add_column('competences', sa.Column('turns', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('competences', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
