"""empty message

Revision ID: 9aefdd0d730a
Revises: 0e9e7452d913
Create Date: 2021-05-02 21:33:05.135615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aefdd0d730a'
down_revision = '0e9e7452d913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('trainings', sa.Column('start_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'start_time')
    op.drop_column('trainings', 'end_time')
    # ### end Alembic commands ###
