"""empty message

Revision ID: abafa1ed4a67
Revises: c6870baa89a4
Create Date: 2020-10-20 21:10:20.903182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abafa1ed4a67'
down_revision = 'c6870baa89a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'track', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.drop_column('track', 'user_id')
    # ### end Alembic commands ###
