"""empty message

Revision ID: b68d23cacec1
Revises: 9aefdd0d730a
Create Date: 2021-05-03 06:31:45.504817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68d23cacec1'
down_revision = '9aefdd0d730a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('duration_max', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('duration_min', sa.Integer(), nullable=True))
    op.drop_column('categories', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'duration_min')
    op.drop_column('categories', 'duration_max')
    # ### end Alembic commands ###
