"""empty message

Revision ID: c15fe3520cfd
Revises: 254dc00e3835
Create Date: 2021-03-23 20:27:50.959718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15fe3520cfd'
down_revision = '254dc00e3835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_ages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('since', sa.Integer(), nullable=True),
    sa.Column('until', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_ages')
    # ### end Alembic commands ###
