"""empty message

Revision ID: ea2b942347df
Revises: c15fe3520cfd
Create Date: 2021-03-23 21:17:05.296260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2b942347df'
down_revision = 'c15fe3520cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_genders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['genders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('gender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'genders', ['gender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_gender_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'gender_id')
    op.drop_table('category_genders')
    op.drop_table('genders')
    # ### end Alembic commands ###
